name: hello-world
on: push
jobs:
  test_django:
    uses: rojre1979/test-repo/blob/dev/.github/workflows/django1.yml
  my-job:
    runs-on: ubuntu-latest
    steps:
      - name: my-step
        run: echo "Hello World!"
